apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: spring-petclinic-istio
build:
  artifacts:
  - image: my-cluster-registry:5000/petclinic-customers-service
    context: petclinic-customers-service
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: my-cluster-registry:5000/petclinic-frontend
    context: petclinic-frontend
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: my-cluster-registry:5000/petclinic-vets-service
    context: petclinic-vets-service
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: my-cluster-registry:5000/petclinic-visits-service
    context: petclinic-visits-service
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
  - manifests/config-map.yaml
  - manifests/customers-service.yaml
  - manifests/petclinic-frontend.yaml
  - manifests/role.yaml
  - manifests/routes.yaml
  - manifests/vets-service.yaml
  - manifests/visits-service.yaml
