---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-frontend
  name: petclinic-frontend
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: petclinic-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-frontend
  name: petclinic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-frontend
  template:
    metadata:
      labels:
        app: petclinic-frontend
    spec:
      containers:
      - name: petclinic-frontend
        image: my-cluster-registry:5000/petclinic-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        ports:
        - containerPort: 8080
      restartPolicy: Always
