---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: petclinic-frontend
  labels:
    account: petclinic-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-frontend
  name: petclinic-frontend
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: petclinic-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-frontend-v1
  labels:
    app: petclinic-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-frontend
      version: v1
  template:
    metadata:
      labels:
        app: petclinic-frontend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: petclinic-frontend
      containers:
      - name: petclinic-frontend
        image: my-cluster-registry:5000/petclinic-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            memory: 1Gi
        ports:
          - containerPort: 8080
      restartPolicy: Always
