---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vets-service
  labels:
    account: vets-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vets-service
  name: vets-service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: vets-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  labels:
    app: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus/"
    spec:
      serviceAccountName: vets-service
      containers:
      - image: my-cluster-registry:5000/petclinic-vets-service:latest
        name: vets-service
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://vets-db-mysql.default.svc.cluster.local:3306/service_instance_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
             secretKeyRef:
               name: vets-db-mysql
               key: mysql-root-password
        ports:
        - containerPort: 8080
      restartPolicy: Always