---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vets-service
  labels:
    account: vets-service
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  labels:
    app: vets-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: vets-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-v1
  labels:
    app: vets-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
      version: v1
  template:
    metadata:
      labels:
        app: vets-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: vets-service
      containers:
      - name: vets-service
        image: ${PULL_IMAGE_REGISTRY}/petclinic-vets-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            memory: 1Gi
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://vets-db-mysql.default.svc.cluster.local:3306/service_instance_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vets-db-mysql
              key: mysql-root-password
